export type Viability = {
    clientName: string,
    cnpj: string,
    nomeFantaisa: string,
    phoneNumber: number,
    email: string,
    postalCodeId: number,
    city: string,
    neighborhood: string,
    state: string,
    address: string,
    number: number,
    complement: string,
    type: string,
    condominio: string,
    block: string,
    apartment: string,
    unionNumber: string,
    operador: string,
}